version: '3.8'

services:
  rmq:
    image: rabbitmq:3.8-management
    container_name: core-calendar_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    restart: "no"
  redis:
    container_name: core-calendar_redis
    image: redis:latest
    restart: "no"
    ports:
      - 6379:6379
  postgres:
      image: postgres:14.4
      container_name: postgres_db_container
      ports:
        - "5432:5432"
      restart: unless-stopped
      environment:
        POSTGRES_DB: ${POSTGRESQL_DB}
        POSTGRES_USER: ${POSTGRESQL_USER}
        POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
